apiVersion: v1
kind: Template
metadata:
  name: template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: test-docker-project
    name: test-docker-project
  spec:
    replicas: 1
    selector:
      app: test-docker-project
      deploymentconfig: dc-test-docker-project
    strategy:
      activeDeadlineSeconds: 21600
      resources:
        requests:
          cpu: 100m
          memory: 100M
    template:
      metadata:
        labels:
          app: test-docker-project
          deploymentconfig: dc-test-docker-project
      spec:
        containers:
          - image: artifacts.mitre.org:8308/int/test-docker-project:0.0.2
            imagePullPolicy: Always
            name: c-test-docker-project
            ports:
              - containerPort: 8000
            resources:
              requests:
                cpu: 100m
                memory: 100M
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
